name: BBD Automation FW

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
      home:
        description: 'Team'
        required: false
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java ${{matrix.java-version}}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{matrix.java-version}}'
          cache: 'maven'

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml test allure:report

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./target/allure-results
          gh_pages: gh-pages
          allure_report: ./target/allure-report
          allure_history: ./target/allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.G_ACCESS_TOKEN }}
#          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target

