name: BBD Automation FW

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
      home:
        description: 'Team'
        required: false
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java ${{matrix.java-version}}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{matrix.java-version}}'
          cache: 'maven'

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml test

      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/cucumber-reports

      #      - name: Cache local Maven repository
      #        uses: actions/cache@v3
      #        with:
      #          path: ~/.m2/repository
      #          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      #          restore-keys: |
      #            ${{ runner.os }}-maven-
      #
      #      - name: Install Google Chrome
      #        run: |
      #          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      #          sudo dpkg -i google-chrome-stable_current_amd64.deb

      #      - name: Download allure
      #        run: |
      #          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.17.3/allure-commandline-2.17.3.zip
      #          sudo unzip allure-commandline-2.17.3.zip -d /allure
      #          export PATH="/allure/allure-2.17.3/bin:${PATH}" && export ALLURE_CONFIG="/allure-config/allure.properties"
      #          rm allure-commandline-2.17.3.zip



#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: allure-report
#          path: target/allure-report
