name: BBD Automation FW

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
      home:
        description: 'Team'
        required: false
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java ${{matrix.java-version}}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{matrix.java-version}}'
          cache: 'maven'

      - name: Build with Maven
        run: |
          mvn package
#          mvn -B package --file pom.xml test allure:report
        continue-on-error: true

#      - name: Send Results and Generate Allure Report
#        uses: Xotabu4/send-to-allure-server-action@1
#        # always() needed because we want report for failed tests as well
#        if: ${{ always() }}
#        with:
#          allure-server-url: 'http://my-allure-server.com:5001/'

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report page to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          publish_dir: allure-history

#      - name: Post the link to the report
#        if: always()
#        uses: Sibz/github-status-action@v1
#        with:
#          authToken: ${{secrets.GITHUB_TOKEN}}
#          context: 'Test report'
#          description: 'Passed'
#          state: 'success'
#          sha: ${{github.event.pull_request.head.sha || github.sha}}
#          target_url: https://github.com/aBin20202/nopCommerce-Selenium-Cucumber


